/* The following code was generated by JFlex 1.4.3 on 23/03/17 13:36 */



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 23/03/17 13:36 from the specification file
 * <tt>brgccf.jflex</tt>
 */
class Mainbrgccf {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\6\1\0\2\4\22\0\1\4\1\10\4\0\1\10"+
    "\1\0\1\11\1\11\1\7\1\10\1\11\1\10\1\11\1\5\1\2"+
    "\11\3\1\0\1\11\1\10\1\10\3\0\22\1\1\32\7\1\1\1"+
    "\1\1\1\1\3\1\1\16\1\12\1\20\1\27\1\15\1\37\1\34"+
    "\1\36\1\24\2\1\1\14\1\31\1\17\1\13\1\22\1\1\1\33"+
    "\1\21\1\26\1\23\1\30\1\35\1\25\1\40\1\1\1\11\1\0"+
    "\1\11\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\1\1\5\1\6"+
    "\17\2\1\7\1\0\11\2\1\10\11\2\1\0\4\2"+
    "\1\11\3\2\1\12\11\2\1\13\2\2\1\14\4\2"+
    "\1\15\1\16\1\17\1\20\10\2\1\21\5\2\1\22"+
    "\1\23\1\2\1\24\1\2\1\25\1\26\1\27\1\2"+
    "\1\30\1\31\1\32\1\0\1\2\1\0\1\2\1\0"+
    "\1\2\1\0\1\2\1\0\1\2\1\0\1\2\1\0"+
    "\1\2\1\0\1\2\1\0\1\2\1\0\1\2\1\0"+
    "\1\2\2\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\41\0\143\0\41\0\204\0\41"+
    "\0\41\0\245\0\306\0\347\0\u0108\0\u0129\0\u014a\0\u016b"+
    "\0\u018c\0\u01ad\0\u01ce\0\u01ef\0\u0210\0\u0231\0\u0252\0\u0273"+
    "\0\u0294\0\u02b5\0\u02d6\0\u02f7\0\u0318\0\u0339\0\u035a\0\u037b"+
    "\0\u039c\0\u03bd\0\u03de\0\102\0\u03ff\0\u0420\0\u0441\0\u0462"+
    "\0\u0483\0\u04a4\0\u04c5\0\u04e6\0\u0507\0\u0528\0\u0549\0\u056a"+
    "\0\u058b\0\u05ac\0\102\0\u05cd\0\u05ee\0\u060f\0\102\0\u0630"+
    "\0\u0651\0\u0672\0\u0693\0\u06b4\0\u06d5\0\u06f6\0\u0717\0\u0738"+
    "\0\41\0\u0759\0\u077a\0\102\0\u079b\0\u07bc\0\u07dd\0\u07fe"+
    "\0\102\0\102\0\102\0\102\0\u081f\0\u0840\0\u0861\0\u0882"+
    "\0\u08a3\0\u08c4\0\u08e5\0\u0906\0\102\0\u0927\0\u0948\0\u0969"+
    "\0\u098a\0\u09ab\0\102\0\102\0\u09cc\0\102\0\u09ed\0\102"+
    "\0\102\0\102\0\u0a0e\0\102\0\102\0\102\0\u0a2f\0\u0a50"+
    "\0\u0a71\0\u0a92\0\u0ab3\0\u0ad4\0\u0af5\0\u0b16\0\u0b37\0\u0b58"+
    "\0\u0b79\0\u0b9a\0\u0bbb\0\u0bdc\0\u0bfd\0\u0c1e\0\u0c3f\0\u0c60"+
    "\0\u0c81\0\u0ca2\0\u0cc3\0\u0ce4\0\41\0\102";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\6\2\10"+
    "\1\11\1\12\1\3\1\13\1\14\1\3\1\15\1\16"+
    "\1\17\1\20\1\3\1\21\1\3\1\22\1\3\1\23"+
    "\1\24\1\25\1\26\1\3\1\27\1\3\1\30\1\3"+
    "\42\0\3\3\6\0\27\3\2\0\2\5\42\0\1\31"+
    "\1\0\1\32\32\0\3\3\6\0\1\3\1\33\25\3"+
    "\1\0\3\3\6\0\3\3\1\34\23\3\1\0\3\3"+
    "\6\0\2\3\1\35\10\3\1\36\13\3\1\0\3\3"+
    "\6\0\3\3\1\37\23\3\1\0\3\3\6\0\2\3"+
    "\1\40\24\3\1\0\3\3\6\0\14\3\1\41\12\3"+
    "\1\0\3\3\6\0\11\3\1\42\15\3\1\0\3\3"+
    "\6\0\5\3\1\43\17\3\1\44\1\3\1\0\3\3"+
    "\6\0\21\3\1\45\2\3\1\46\2\3\1\0\3\3"+
    "\6\0\1\3\1\47\25\3\1\0\3\3\6\0\4\3"+
    "\1\50\22\3\1\0\3\3\6\0\14\3\1\51\11\3"+
    "\1\52\1\0\3\3\6\0\3\3\1\53\23\3\1\0"+
    "\3\3\6\0\24\3\1\54\2\3\1\0\3\3\6\0"+
    "\4\3\1\55\22\3\6\31\1\0\32\31\7\32\1\56"+
    "\31\32\1\0\3\3\6\0\1\3\1\57\25\3\1\0"+
    "\3\3\6\0\5\3\1\60\21\3\1\0\3\3\6\0"+
    "\7\3\1\61\17\3\1\0\3\3\6\0\14\3\1\62"+
    "\12\3\1\0\3\3\6\0\23\3\1\63\3\3\1\0"+
    "\3\3\6\0\4\3\1\64\22\3\1\0\3\3\6\0"+
    "\4\3\1\65\22\3\1\0\3\3\6\0\1\66\26\3"+
    "\1\0\3\3\6\0\14\3\1\67\12\3\1\0\3\3"+
    "\6\0\11\3\1\70\15\3\1\0\3\3\6\0\12\3"+
    "\1\71\14\3\1\0\3\3\6\0\12\3\1\72\14\3"+
    "\1\0\3\3\6\0\12\3\1\73\14\3\1\0\3\3"+
    "\6\0\21\3\1\74\5\3\1\0\3\3\6\0\7\3"+
    "\1\75\17\3\1\0\3\3\6\0\14\3\1\76\12\3"+
    "\1\0\3\3\6\0\12\3\1\77\14\3\1\0\3\3"+
    "\6\0\2\3\1\100\24\3\5\32\1\101\1\32\1\56"+
    "\31\32\1\0\3\3\6\0\2\3\1\102\24\3\1\0"+
    "\3\3\6\0\22\3\1\103\4\3\1\0\3\3\6\0"+
    "\3\3\1\104\23\3\1\0\3\3\6\0\3\3\1\105"+
    "\23\3\1\0\3\3\6\0\7\3\1\106\17\3\1\0"+
    "\3\3\6\0\14\3\1\107\12\3\1\0\3\3\6\0"+
    "\2\3\1\110\24\3\1\0\3\3\6\0\3\3\1\111"+
    "\23\3\1\0\3\3\6\0\7\3\1\112\17\3\1\0"+
    "\3\3\6\0\15\3\1\113\11\3\1\0\3\3\6\0"+
    "\5\3\1\114\21\3\1\0\3\3\6\0\12\3\1\115"+
    "\14\3\1\0\3\3\6\0\14\3\1\116\12\3\1\0"+
    "\3\3\6\0\11\3\1\117\15\3\1\0\3\3\6\0"+
    "\2\3\1\120\24\3\1\0\3\3\6\0\7\3\1\121"+
    "\17\3\1\0\3\3\6\0\3\3\1\122\23\3\1\0"+
    "\3\3\6\0\14\3\1\123\12\3\1\0\3\3\6\0"+
    "\5\3\1\124\21\3\1\0\3\3\6\0\7\3\1\125"+
    "\17\3\1\0\3\3\6\0\12\3\1\126\14\3\1\0"+
    "\3\3\6\0\12\3\1\127\14\3\1\0\3\3\6\0"+
    "\5\3\1\130\21\3\1\0\3\3\6\0\3\3\1\131"+
    "\23\3\1\0\3\3\6\0\21\3\1\132\5\3\1\0"+
    "\3\3\6\0\3\3\1\133\23\3\1\0\3\3\6\0"+
    "\3\3\1\134\23\3\1\0\3\3\6\0\4\3\1\135"+
    "\22\3\1\0\3\3\6\0\24\3\1\136\2\3\1\0"+
    "\3\3\6\0\15\3\1\137\11\3\1\0\3\3\6\0"+
    "\6\3\1\140\20\3\1\0\3\3\6\0\6\3\1\141"+
    "\20\3\1\0\3\3\6\0\22\3\1\142\4\3\1\0"+
    "\3\3\6\0\17\3\1\143\7\3\1\0\3\3\6\0"+
    "\5\3\1\144\21\3\1\0\3\3\6\0\5\3\1\145"+
    "\21\3\1\0\3\3\6\0\7\3\1\146\17\3\1\147"+
    "\3\150\2\147\1\0\3\147\27\150\13\0\1\151\26\0"+
    "\3\3\6\0\1\3\1\152\25\3\23\0\1\153\16\0"+
    "\3\3\6\0\11\3\1\154\15\3\26\0\1\155\13\0"+
    "\3\3\6\0\14\3\1\156\12\3\6\157\1\0\33\157"+
    "\3\160\2\157\1\0\3\157\27\160\22\0\1\161\17\0"+
    "\3\3\6\0\10\3\1\162\16\3\33\0\1\163\6\0"+
    "\3\3\6\0\21\3\1\164\5\3\24\0\1\165\15\0"+
    "\3\3\6\0\12\3\1\166\14\3\17\0\1\167\22\0"+
    "\3\3\6\0\5\3\1\170\21\3\26\0\1\171\13\0"+
    "\3\3\6\0\14\3\1\172\12\3\14\0\1\173\25\0"+
    "\3\3\6\0\2\3\1\174\24\3\17\0\1\175\22\0"+
    "\3\3\6\0\5\3\1\176\21\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3333];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\1\1\2\11"+
    "\20\1\1\0\23\1\1\0\22\1\1\11\45\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Mainbrgccf(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Mainbrgccf(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { System.out.println("Token INT ("+yytext()+")");
          }
        case 28: break;
        case 11: 
          { System.out.println("Token COMMENT_EXT ("+yytext()+")");
          }
        case 29: break;
        case 2: 
          { System.out.println("Token ID ("+yytext()+")");
          }
        case 30: break;
        case 5: 
          { System.out.println("Token OPERATOR ("+yytext()+")");
          }
        case 31: break;
        case 22: 
          { System.out.println("Token PUBLIC");
          }
        case 32: break;
        case 18: 
          { System.out.println("Token WHILE");
          }
        case 33: break;
        case 16: 
          { System.out.println("Token MAIN");
          }
        case 34: break;
        case 26: 
          { System.out.println("Token EXTENDS");
          }
        case 35: break;
        case 9: 
          { System.out.println("Token NEW");
          }
        case 36: break;
        case 23: 
          { System.out.println("Token STRING");
          }
        case 37: break;
        case 20: 
          { System.out.println("Token LENGTH");
          }
        case 38: break;
        case 12: 
          { System.out.println("Token ELSE");
          }
        case 39: break;
        case 13: 
          { System.out.println("Token TRUE");
          }
        case 40: break;
        case 25: 
          { System.out.println("Token BOOLEAN");
          }
        case 41: break;
        case 27: 
          { System.out.println("Token SYSTEM.OUT.PRINTLN");
          }
        case 42: break;
        case 1: 
          { throw new RuntimeException("Caractere ilegal! '" +
                                              yytext() + "' na linha: " + yyline + ", coluna: " + yycolumn);
          }
        case 43: break;
        case 21: 
          { System.out.println("Token STATIC");
          }
        case 44: break;
        case 8: 
          { System.out.println("Token IF");
          }
        case 45: break;
        case 10: 
          { System.out.println("Token INT");
          }
        case 46: break;
        case 24: 
          { System.out.println("Token RETURN");
          }
        case 47: break;
        case 17: 
          { System.out.println("Token CLASS");
          }
        case 48: break;
        case 19: 
          { System.out.println("Token FALSE");
          }
        case 49: break;
        case 14: 
          { System.out.println("Token THIS");
          }
        case 50: break;
        case 7: 
          { System.out.println("Token COMMENT_LINE ("+yytext()+")");
          }
        case 51: break;
        case 15: 
          { System.out.println("Token VOID");
          }
        case 52: break;
        case 4: 
          { 
          }
        case 53: break;
        case 6: 
          { System.out.println("Token DELIMITATION ("+yytext()+")");
          }
        case 54: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Mainbrgccf <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Mainbrgccf scanner = null;
        try {
          scanner = new Mainbrgccf( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
